fcfmramos/view/main.py
from flask import Blueprint
from flask import render_template, redirect, url_for, request
from sqlalchemy import or_

from fcfmramos.view.auth import is_logged_in
from fcfmramos.model import db
from fcfmramos.model.ucampus import Ramo

bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    page = request.args.get('page', 1, type=int)
    search_query = request.args.get('search', '')

    # ramos = db.session.execute(db.select(Ramo)).scalars()
    query = db.select(Ramo)
    if search_query:
        query = query.where(or_(
            Ramo.nombre.ilike(f"%{search_query}%"),
            Ramo.codigo.ilike(f"%{search_query}%")
        ))
    ramos = db.paginate(query, page=page, per_page=20)

    return render_template(
        "index.html",
        ramos=ramos,
        serialized_ramos=[ramo.serialize() for ramo in ramos.items]
    )


@bp.route("/profile")
def profile():
    if not is_logged_in():
        return redirect(url_for("auth.login"))

    return render_template("profile.html")

fcfmramos/views/auth.py
import json

from functools import wraps

from flask import session, redirect, flash, url_for, render_template
from flask import Blueprint
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email, Length

import pyrebase

bp = Blueprint("auth", __name__)


firebase = pyrebase.initialize_app(json.load(open("fbconfig.json")))
auth = firebase.auth()


class LoginForm(FlaskForm):
    email = StringField(
        "Correo (@ug.uchile.cl)", validators=[DataRequired(), Email()]
    )
    password = PasswordField(
        "Contraseña", validators=[DataRequired(), Length(min=8)]
    )
    submit = SubmitField("Ingresar")


def validate_email_domain(form, field):
    if not field.data.endswith("@ug.uchile.cl"):
        raise ValidationError("El correo debe terminar en @ug.uchile.cl")


class SignupForm(FlaskForm):
    email = StringField(
        "Correo (@ug.uchile.cl)",
        validators=[DataRequired(), Email(), validate_email_domain],
    )
    password = PasswordField(
        "Contraseña", validators=[DataRequired(), Length(min=8)]
    )
    submit = SubmitField("Crear cuenta")


class RecoverPasswordForm(FlaskForm):
    email = StringField(
        "Correo (@ug.uchile.cl)",
        validators=[DataRequired(), Email(), validate_email_domain],
    )
    submit = SubmitField("Recuperar contraseña")


def is_logged_in():
    # Is email verified
    return "user" in session


def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if not is_logged_in():
            return {"message": "Unauthorized"}, 401
        return f(*args, **kwargs)

    return wrap


def is_verified():
    if not is_logged_in():
        return False
    return auth.get_account_info(session["user"])["users"][0]["emailVerified"]


def login_email_password(email, password):
    user = auth.sign_in_with_email_and_password(email, password)
    session["user"] = user["idToken"]
    session["username"] = email.split("@")[0]


@bp.route("/signup", methods=["POST", "GET"])
def signup():
    form = SignupForm()

    if "user" in session:
        return {"message": "Ya estás ingresadx"}, 200

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        try:
            auth.create_user_with_email_and_password(email, password)
            login_email_password(email, password)

            try:
                auth.send_email_verification(session["user"])
            except Exception as e:
                print(e)
                flash(
                    "Error en envío de correo, por favor contactar al admin",
                    "error",
                )
                return redirect(url_for("main.index"))

            flash("Cuenta creada", "success")
            return redirect(url_for("main.index"))
        except Exception as e:
            print(e)
            flash("Error en creación de cuenta", "error")
            return redirect(url_for("signup"))

    return render_template("signup.html", form=form)


@bp.route("/forgot_password", methods=["POST", "GET"])
def forgot_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        email = form.email.data
        try:
            auth.send_password_reset_email(email)
            flash("Correo de recuperación enviado a tu correo", "success")
            return redirect(url_for("main.index"))
        except Exception as e:
            print(e)
            flash("Error en envío de correo de recuperación", "error")
            return redirect(url_for("forgot_password"))

    return render_template("forgot_password.html", form=form)


@bp.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if "user" in session:
        return {"message": "Ya estás ingresadx"}, 200

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        try:
            login_email_password(email, password)

            flash("Ingreso exitoso", "success")
            return redirect(url_for("main.index"))
        except Exception as e:
            print(e)
            flash("Error en inicio de sesión", "error")
            return redirect(url_for("login"))

    return render_template("login.html", form=form)


@bp.route("/logout")
def logout():
    session.clear()
    flash("Sesión cerrada", "success")
    return redirect(url_for("main.index"))

fcfmramos/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RFCFM | {% block title %}{% endblock %}</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block css %}{% endblock %}

    <script defer src="https://cdn.jsdelivr.net/npm/@imacrayon/alpine-ajax@0.5.0/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    {% block js %}{% endblock %}
</head>
<body>
    <section id="toaster" class="gui-toast-group">
    </section>

    {% include '/partials/_header.html' %}

    <main>{% block content %}{% endblock %}</main>

    <script src="{{ url_for('static', filename='js/toast.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        newToast('{{ message }}', '{{ category }}');
                    {% endfor %}
                {% endif %} 
            {% endwith %}
        });
    </script>
</body>
</html>

fcfmramos/templates/_macros.html
{% macro icon(icon_name) %}
<svg class="icon i-{{icon_name}}">
	<use
		href="{{ url_for('static', filename='img/feather-sprite.svg') }}#{{ icon_name }}"
	/>
</svg>
{% endmacro %}

fcfmramos/templates/catalog.html
{% from "macros/_icon.html" import icon %}
{% from "macros/_course_card.html" import course_card %}
{% from "macros/_subplan_card.html" import subplan_card %}
{% extends "_base.html" %} {% block title
%}Home{% endblock %} {% block content %}
<h1>{{ subplan.nickname if subplan.nickname else subplan.nombre }}</h1>

<section>
    {% for child in subplans %}
        {% if not child.absorb %}
            {{ subplan_card(child) }}
        {% endif %}
    {% endfor %}
</section>


<section x-data="courseData()">
	<div role="toolbar" aria-label="Busqueda, filtros y ordenamiento" x-show="sourceData.length != 0">
		<fieldset class="search" role="search">
			<input
				id="search"
				x-ref="searchField"
				x-model="search"
				x-on:keydown.window.prevent.slash="$refs.searchField.focus()"
				placeholder="Buscar un curso..."
				type="search"
			/>
		</fieldset>

		<fieldset class="radio">
			<legend>Ordenar por:</legend>
			{% for key, name in { 'nombre': 'Nombre', 'codigo': 'Código', 'none': 'Ultima dictación' }.items() %}
			<label for="sort-{{ key }}" title="{{ name }}">
				<input
					type="radio"
					value="{{ key }}"
					x-model="sorting"
					name="sort"
					id="sort-{{ key }}"
				/>
                {{ name }}
			</label>
			{% endfor %}
		</fieldset>
	</div>

	<div id="courses">
		<template x-for="course in filteredCourses" :key="course.id">
            {{ course_card(course) }}
		</template>
	</div>

	<script>
		function normalize(string) {
		    return string.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
		}

        function courseData() {
            return {
                search: "",
                sorting: "none",
                myForData: sourceData,
		        get filteredCourses() {
		            const searchString = normalize(this.search)

		            return this.myForData.filter((ramo) => {
                        const matchesSearch = normalize(ramo.nombre).includes(searchString) || normalize(ramo.codigo).includes(searchString);
                        if (!matchesSearch) return false;

		                return true;
		            }).sort((a, b) => {
                        if (this.sorting === "nombre") {
                            return a.nombre.localeCompare(b.nombre);
                        } else if (this.sorting === "codigo") {
                            return a.codigo.localeCompare(b.codigo);
                        } else {
                            return b.ultima_dictacion.localeCompare(a.ultima_dictacion);
                        }
                    })
		        }
            }
        }

		const sourceData = {{ courses | tojson | safe }};
	</script>
</section>
{% endblock %}

fcfmramos/templates/index.html
{% from "macros/_icon.html" import icon %}
{% from "macros/_course_card.html" import course_card %}
{% from "macros/_pagination.html" import pagination %}
{% extends "_base.html" %} {% block title
%}Home{% endblock %} {% block content %}
<h1>Ramos FCFM</h1>

<div role="toolbar">
    <form action="{{ url_for('main.index') }}" method="get">
        <input type="text" name="search" placeholder="Buscar ramo..." value="{{ search_query }}">
        <button type="submit">Buscar</button>
    </form>
</div>

<section>
	<div id="courses">
		{% for ramo in serialized_ramos %}
            {{ course_card(ramo) }}
        {% endfor %}
	</div>

    <div>
        {{ pagination(ramos, "main.index") }}
    </div>
</section>
{% endblock %}

fcfmramos/templates/login.html
{% extends "_base.html" %}

{% block title %}Ingreso{% endblock %}

{% block content %}
    <h2>Ingreso</h2>
    <form method="post">
        {{ form.hidden_tag() }}

        <div>
            {{ form.email.label }}
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>{{ form.submit() }}</div>
    </form>

    <a href="{{ url_for('auth.forgot_password') }}">Recuperar contraseña</a>
{% endblock %}

fcfmramos/templates/oldindex.html
{% from "macros/_icon.html" import icon %}
{% from "macros/_course_card.html" import course_card %}
{% from "macros/_pagination.html" import pagination %}
{% extends "_base.html" %} {% block title
%}Home{% endblock %} {% block content %}
<h1>Ramos FCFM</h1>

<section x-data="courseData()">
	<div role="toolbar" aria-label="Busqueda, filtros y ordenamiento">
		<fieldset class="search" role="search">
			<input
				id="search"
				x-ref="searchField"
				x-model="search"
				x-on:keydown.window.prevent.slash="$refs.searchField.focus()"
				placeholder="Buscar un curso..."
				type="search"
			/>
		</fieldset>

		<fieldset class="radio">
			<legend>Ordenar por:</legend>
			{% for key, name in { 'nombre': 'Nombre', 'codigo': 'Código', 'none': 'Ultima dictación' }.items() %}
			<label for="sort-{{ key }}" title="{{ name }}">
				<input
					type="radio"
					value="{{ key }}"
					x-model="sorting"
					name="sort"
					id="sort-{{ key }}"
				/>
                {{ name }}
			</label>
			{% endfor %}
		</fieldset>
	</div>

	<div id="courses">
		<template x-for="course in filteredCourses" :key="course.id">
            {{ course_card(course) }}
		</template>
	</div>

    <div>
        {{ pagination(ramos, "main.index") }}
    </div>

	<script>
		function normalize(string) {
		    return string.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
		}

        function courseData() {
            return {
                search: "",
                sorting: "none",
                myForData: sourceData,
		        get filteredCourses() {
		            const searchString = normalize(this.search)

		            return this.myForData.filter((ramo) => {
                        const matchesSearch = normalize(ramo.nombre).includes(searchString) || normalize(ramo.codigo).includes(searchString);
                        if (!matchesSearch) return false;

		                return true;
		            }).sort((a, b) => {
                        if (this.sorting === "nombre") {
                            return a.nombre.localeCompare(b.nombre);
                        } else if (this.sorting === "codigo") {
                            return a.codigo.localeCompare(b.codigo);
                        } else {
                            return b.ultima_dictacion.localeCompare(a.ultima_dictacion);
                        }
                    })
		        }
            }
        }

		const sourceData = {{ serialized_ramos | tojson | safe }};
	</script>
</section>
{% endblock %}

fcfmramos/templates/profile.html
{% extends "_base.html" %}

{% block title %}Mis reseñas{% endblock %}

{% block content %}
    <h1>Mis reseñas</h1>
    {% if is_verified %}
        <a href="{{ url_for('auth.forgot_password') }}">Cambiar contraseña</a>

        <p>Estas son tus reseñas:</p>
        <ul>
            {% for review in reviews %}
                <li>{{ review.title }} - {{ review.rating }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>Por favor verifica tu correo para poder dejar reseñas.</strong>
    {% endif %}
{% endblock %}
```

fcfmramos/templates/signup.html
{% extends "_base.html" %}

{% block title %}Crear Cuenta{% endblock %}

{% block content %}
    <h2>Crear cuenta</h2>
    <form method="post">
        {{ form.hidden_tag() }}

        <div>
            {{ form.email.label }}
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>

        <div>{{ form.submit() }}</div>
    </form>
{% endblock %}